### ISSUE TITLE
Expo 51?

### ISSUE THREAD

**Issue by Armster15** [Armster15/expo-xml-font#4]
[Expo 51 came out today.](https://expo.dev/changelog/2024/05-07-sdk-51) This library is currently untested for Expo 51. If anyone has already upgraded it would be appreciated if someone could let me know if it works/doesn't work.

**Comment by djMax** [comment]
I'm starting this now. We use expo-font now, I assume this can layer on top of that?

**Comment by Armster15** [comment]
If you're using expo-font then there isn't much point in using this config plugin since expo-font handles bundling the fonts for you and everything.

**Comment by nkoynov** [comment]
I think we still need this library because expo-font does not allow setting fontFamily and fontWeight separately on Android. I couldn't find a way to make expo-font config plugin to add the custom font as an XML resource on android.

**Comment by Armster15** [comment]
Yea that's exactly something that fits the use case of this config plugin. It should work with Expo 51 based on some quick rudimentary testing I did but if not feel free to let me know here or open a new issue.
